### ISSUE TITLE
Does this work with other flutter plugins?

### ISSUE THREAD

**Issue by TexMexMax** [JulianAssmann/flutter_background#1]
Gonna try to do bluetooth.

**Comment by JulianAssmann** [comment]
Yes, it should work with other plugins, as the whole isolate keeps running. However, I only tested it with the flutter_local_notifications plugin.

**Comment by JulianAssmann** [comment]
Do you have any updates on this? Otherwise I would close this issue.

**Comment by JulianAssmann** [comment]
I will close this issue now, feel free to reopen it.

**Comment by yo80106** [comment]
@TexMexMax Did you successfully implement the plugin with Bluetooth? Recently, I am trying to do a similar thing. Thank you in advance.
