### ISSUE TITLE
Task 'assembleAarRelease' not found

### ISSUE THREAD

**Issue by khyvez** [JulianAssmann/flutter_background#13]
![fb](https://user-images.githubusercontent.com/8803979/105302751-56b95100-5bf6-11eb-8f3c-38e3d56b4296.png)
Hello, I'm having trouble to build my app

**Comment by JulianAssmann** [comment]
Does [this](https://github.com/flutter/flutter/issues/43704) or [this](https://github.com/gradle/gradle/issues/6026) solve the issue?

**Comment by JulianAssmann** [comment]
Please feel free to reopen the issue if the problem remains.
