### ISSUE TITLE
What happens if you call initialize twice?

### ISSUE THREAD

**Issue by Timmmm** [JulianAssmann/flutter_background#16]
Small clarification needed for the docs - what happens if you call initialize after it's already been called?

From the code it looks like it is fine to me - and probably a reasonable idea just to call initialize() before enable() every time. But it would be good to clarify that in the docs.

**Comment by JulianAssmann** [comment]
Thank you for the suggestion. I improved the initialize method and tried out calling it twice, and the code as well as the test suggest that there is no problem calling it as many times as you want. The documentation is now updated.
