### ISSUE TITLE
Location continuelly

### ISSUE THREAD

**Issue by gaoyx-tech** [JulianAssmann/flutter_background#20]
hello,I am a Chinese flutter developer,I used this project for location continuelly,even if screen off or let the app back to background.I use HuaWei Meta20,I found that if screen off after seconds the service will stop,it cannot location again.

**Comment by JulianAssmann** [comment]
I am not sure how Huawei handles background execution of apps, as every OEM handles it a bit differently. What code are you trying to run where? Do you have any logs that could reveal the issue?
I did not test this package with geolocation services, but check out other plugins specifically made for this purpose like [flutter_background_geolocation](https://pub.dev/packages/flutter_background_geolocation) or [background_locator](https://pub.dev/packages/background_locator).

**Comment by gaoyx-tech** [comment]
ok,thanks for reply.

**Comment by JulianAssmann** [comment]
You're welcome. Please feel free to reopen the issue at any time.

**Comment by alkebuware** [comment]
I was able to fix this problem recently and wanted to post a solution if anyone comes across this issue. In your Flutter app's Android's AndroidManifest.xml <application> tag add the following <service>

```
<service android:name="de.julianassmann.flutter_background.IsolateHolderService"
                 android:foregroundServiceType="location" />
```
