### ISSUE TITLE
remove initialize message

### ISSUE THREAD

**Issue by AbanoubWagih94** [JulianAssmann/flutter_background#48]
how to remove initialize message appear one app install at first time

**Comment by JulianAssmann** [comment]
Sorry, I don't quite understand your question. Do you only want the message to appear on the first app launch after installation?

**Comment by AbanoubWagih94** [comment]
@JulianAssmann  yes

**Comment by AbanoubWagih94** [comment]
@JulianAssmann no i don't want the message appear

**Comment by JulianAssmann** [comment]
That isn't possible, because the OS requires the user to give permission to the app.

**Comment by AbanoubWagih94** [comment]
if i remove battery optimization from manifest will cause any problem ?!

**Comment by JulianAssmann** [comment]
Yes. The Android OS will not allow any background execution without letting the user know about it, which is perfectly understandable from my POV.

**Comment by AbanoubWagih94** [comment]
@JulianAssmann there is any way to ignore asking about battery optimization ?!
