### ISSUE TITLE
iOS Background Operations

### ISSUE THREAD

**Issue by mado-bohsali** [JulianAssmann/flutter_background#52]
As per your package description, you have mentioned that iOS is not supported. How should I make sure of you package for iOS? In brief, all I want to do is do save the current open quiz (1 question and its options) in the background. That said, in case the app is back online, I redirect the user to the last opened question.

**Comment by JulianAssmann** [comment]
Sorry, I don't quite understand? Are you asking me if the package is working on iOS, if it *could* work on iOS or if you should try to implement the package for iOS?

**Comment by mado-bohsali** [comment]
Yes i'm asking if it works on iOS since you mentioned on pub.dev "iOS is currently not supported."

**Comment by JulianAssmann** [comment]
No, unfortunately not. As you can see, the iOS implementation is empty. I don't think something like that is even possible on iOS.
