### ISSUE TITLE
Foreground Service closes after app swiped up/closed from multitasking panel

### ISSUE THREAD

**Issue by MuhammadFahidSarker** [JulianAssmann/flutter_background#59]
The plugin works fine when the app is focused or in the background. But once, once the app is closed by swiping up from the multitasking area, the notification is removed. 

APP in Focus:
![Screenshot_20220622-215224__01](https://user-images.githubusercontent.com/80589556/175076656-2bd216d4-b24d-415b-bc5f-948c69637560.jpg)

App In Background but not closed:
![Screenshot_20220622-215234__01](https://user-images.githubusercontent.com/80589556/175076643-9164b725-ab9b-4c03-8897-3f9fb38e1d8e.jpg)

App Closed from muli-tasking view:
![Screenshot_20220622-215240__01](https://user-images.githubusercontent.com/80589556/175076638-dbaaf05e-3a30-481d-b8f7-f393c7d1109e.jpg)

Note: The white dot is the notification

Is this normal behavior? Shouldn't it keep the app alive even after swiped up?

Objective of the app: Prevent the app from being killed to ensure timely alarm firing by the android alarm manager

Device: Oneplus 7 - Android 11

**Comment by JulianAssmann** [comment]
This is intentional behavior introduced by #10. As closing the app is an intentional action by the user, this intent has to be respected by apps. The isolate the app runs in should be killed either way, so keeping the foreground notification probably does not achieve the desired effect.
I don't quite understand the reason you need the app running in the background in order for the alarm manager to work.

**Comment by MuhammadFahidSarker** [comment]
I see. Thank you for clarification. 

The thing is Android probably kills my app process after it has been closed for few days. It is a prayer notification app, so notifying prayer time everyday and calculating the next time should continue happening even if user does not open the app for weeks. But, Alarm manager does not fire alarms on due time. Hence, I wanted to keep a process running to make sure it keeps running. Any help would be appreciated 🤠
