### ISSUE TITLE
example build error

### ISSUE THREAD

**Issue by yakupbaser** [JulianAssmann/flutter_background#6]
hi,

i tryed to bu build your example and i got an error. firstly i upgraded packages. I use flutter last version. Error output is:

Macs-MacBook-Pro:example macpro$ flutter build apk --target-platform android-arm64
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/pc/Documents/flutter_background-master/example/build/app/intermediates/flutter/profile/libs.jar.
         > Transform's input file does not exist: /Users/pc/Documents/flutter_background-master/example/build/app/intermediates/flutter/profile/libs.jar. (See https://issuetracker.google.com/issues/158753935)
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 42s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      43.4s
Gradle task assembleRelease failed with exit code 1

**Comment by JulianAssmann** [comment]
Hey,

this seems to be an issue not related to the package. Could you please try again with

```
flutter build apk --debug
flutter build apk --profile
flutter build apk --release
```

as suggested [here](https://stackoverflow.com/questions/62394034/flutter-can-not-build-android-apk)?

**Comment by yakupbaser** [comment]
yes it worked,
i had tried in ios i guess :)
Thanks for your help.

**Comment by JulianAssmann** [comment]
Perfect, thanks for letting me know :+1:
