### ISSUE TITLE
[BUG] Current published version isn't supported on build gradle 7.3+

### ISSUE THREAD

**Issue by jpeiffer** [JulianAssmann/flutter_background#65]
**Describe the bug**
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_background' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**To Reproduce**
Using the following settings in the Android `build.gradle`:

```gradle
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Expected behavior**
Working builds.  It looks like the issue has already been addressed on the `master` branch and may just require a new release to pub.dev to resolve.

**Screenshots**
n/a

**Smartphone:**

n/a

<details>
  <summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.6 on channel stable at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (7 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at ...
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = ...
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at ...
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at ...
    • Flutter extension version 3.50.0

```
</details>

**Comment by JaffaKetchup** [comment]
Hey @JulianAssmann, can you please have a look into this when you get time?

**Comment by aytunch** [comment]
Hi @JulianAssmann Are you still maintaining this plugin? A lot of Flutter packages rely on this awesome package. We would be really glad if you could update this lib. Thank you

**Comment by JulianAssmann** [comment]
Hi @aytunch,
I currently do not own an Android device anymore. I'm trying to get my hands on one, but keep in mind I'm doing this for free and don't want to invest into hardware for the sole purpose of supporting this library.

**Comment by JaffaKetchup** [comment]
@JulianAssmann I can confirm that the master branch does not have this issue, so this just needs a new release. I understand that you can't invest any money into hardware for testing, but this should already be tested, and is working :)

**Comment by JulianAssmann** [comment]
@JaffaKetchup I'm relying on your judgement and have released the current master branch to [pub.dev](https://pub.dev/packages/flutter_background). It would be great if you could confirm the current version is still working.
Thank you all for your contributions!

**Comment by JaffaKetchup** [comment]
@JulianAssmann I'll report to the people waiting on this. Thanks :)
