### ISSUE TITLE
I am not getting the persistent notification

### ISSUE THREAD

**Issue by kgoofori** [JulianAssmann/flutter_background#72]
I am not able to get the app running with the persistent notification even after running ` FlutterBackground.enableBackgroundExecution()` successfully.

I am testing on Samsung A51 running android 12.

[✓] Flutter (Channel stable, 3.7.10, on macOS 12.5.1 21G83 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)

environment:
  sdk: '>=2.18.6 <3.0.0'
  
dependencies:
  flutter_background: ^1.2.0

**Comment by Muhammad-Mohsen** [comment]
I think this is related to https://github.com/JulianAssmann/flutter_background/issues/69
I'd try the solution by @jakoss to add the service to the AndroidManifset manually

`<service
    android:name="de.julianassmann.flutter_background.IsolateHolderService"
    android:exported="false" />
`

**Comment by KhaledYussef** [comment]
<service android:name="de.julianassmann.flutter_background.IsolateHolderService" android:exported="true" />

**Comment by KhaledYussef** [comment]
`<service android:name="de.julianassmann.flutter_background.IsolateHolderService" android:exported="true" />`

**Comment by Aturex1** [comment]
Not working here either.
I'm using Android 14

`flutter_background: ^1.2.0`

**Comment by JulianAssmann** [comment]
Thanks for creating the issue. Can you please upgrade to the new version of the plugin (1.3.0), update your `AndroidManifest.xml` according to the new `README` (specifically including the foreground service types). This should fix this issue. If not, please feel free to re-open the issue.

**Comment by TNorbury** [comment]
I was having this issue. I fixed it by requesting `Permission.notification` manually via the `permission_handler` package
