### ISSUE TITLE
[Android] Add ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS as an option to obtain excemption from battery optimizations

### ISSUE THREAD

**Issue by JulianAssmann** [JulianAssmann/flutter_background#8]
On android, add [ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS](https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS) as an option to obtain excemption from battery optimizations, as declaring [REQUEST_IGNORE_BATTERY_OPTIMIZATIONS](https://developer.android.com/reference/android/Manifest.permission.html#REQUEST_IGNORE_BATTERY_OPTIMIZATIONS) might lead to a ban of the app in the Play Store, "unless the core function of the app is adversely affected" (see the note [here](https://developer.android.com/training/monitoring-device-state/doze-standby.html#support_for_other_use_cases))

**Comment by datdescartes** [comment]
@JulianAssmann 
As [option to not request battery optimization permission](https://github.com/JulianAssmann/flutter_background/commit/37ecfb347b245c5d3f3f9a8d413d03f3fd8a6786) is added, could you release new version to pub.dev?
The[ current version(1.1.0)](https://pub.dev/packages/flutter_background) doesn't reflect latest code

**Comment by JulianAssmann** [comment]
@datdescartes Release 1.2.0 should now incorporate these changes :)
