### ISSUE TITLE
Add permissions to plugin's AndroidManifest.xml

### ISSUE THREAD

**Issue by larssn** [JulianAssmann/flutter_background#82]
Any reason why the 3 permissions below aren't added to the plugin's AndroidManifest.xml?
Gradle is pretty good at merging manifest files when building, so there's shouldn't be any reason to ask the consumer to put these in the app's manifest.

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
```

**Comment by JulianAssmann** [comment]
Thank you for creating the issue.
This should be resolved by #80.
