### ISSUE TITLE
[BUG] Error while building/running the app for Android

### ISSUE THREAD

**Issue by iAbdulaziz93** [JulianAssmann/flutter_background#87]
**Describe the bug**
When I try to run my Flutter app for Android, the below error appears in the build phase, this error only occurs when I add the `flutter_background: ^1.2.0` package to the `pubspec.yaml` file.

**To Reproduce**
1. Add the package above to your Flutter project.
2. Choose an Android device.
3. Try to run your app.

**Expected behavior**
The project/app should run without issues.

**Screenshots**
![image](https://github.com/user-attachments/assets/d52b67cb-366b-4b50-adfc-99cbb9095b6f)

**Smartphone:**

 - Device: HONOR Pad X9.
 - OS: MagicOS 7.1 (Android 13).

[Logs.txt](https://github.com/user-attachments/files/16409223/Logs.txt)

<details>
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-SA)
    • Flutter version 3.22.3 on channel stable at /Users/abdulaziz/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (12 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/abdulaziz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • ELN L09 (mobile)                • ADYX9X4205G01117      • android-arm64  • Android 13 (API 33)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.73
    ! Error: Browsing on the local area network for ‏iPhone ‏عز. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</details>

**Comment by JulianAssmann** [comment]
Please update to the latest version (1.3.0), which updates the Gradle syntax to the declarative plugin blocks.
